// Embedding provider abstraction — docs/specs/MR-ARQ-arquitetura-tecnica-mestra.md
// §19/§47 ("criar EmbeddingProvider... nunca chamar um fornecedor
// diretamente espalhado pelo código"). OpenAI is the provider the product
// owner chose for Fase 4 (docs/DECISIONS.md, 11/09/2026). Swapping
// providers later means reimplementing embedText() here, not touching the
// two Edge Functions that call it.

export const EMBEDDING_MODEL = "text-embedding-3-small";
export const EMBEDDING_DIMENSIONS = 1536;
// Bump this if EMBEDDING_MODEL (or its config) ever changes — never
// compare embeddings generated by different model/version pairs
// (docs/DATA_MODEL.md).
export const EMBEDDING_VERSION = "1";

/** Returns one embedding vector per input string, in the same order. */
export async function embedTexts(texts: string[]): Promise<number[][]> {
  const apiKey = Deno.env.get("OPENAI_API_KEY");
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY não configurada (Project Settings → Secrets no Lovable).");
  }

  const response = await fetch("https://api.openai.com/v1/embeddings", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model: EMBEDDING_MODEL, input: texts }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Falha ao gerar embeddings (OpenAI ${response.status}): ${errorText}`);
  }

  const data = (await response.json()) as { data: { embedding: number[]; index: number }[] };
  return data.data.sort((a, b) => a.index - b.index).map((item) => item.embedding);
}

/** pgvector's text input format is a bare bracketed list — JSON.stringify of a number[] already matches it. */
export function toVectorLiteral(embedding: number[]): string {
  return JSON.stringify(embedding);
}
