/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBrainRouteImport } from './routes/_authenticated/brain'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReflectionsIndexRouteImport } from './routes/_authenticated/reflections/index'
import { Route as AuthenticatedReflectionsNewRouteImport } from './routes/_authenticated/reflections/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrainRoute = AuthenticatedBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReflectionsIndexRoute =
  AuthenticatedReflectionsIndexRouteImport.update({
    id: '/reflections/',
    path: '/reflections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReflectionsNewRoute =
  AuthenticatedReflectionsNewRouteImport.update({
    id: '/reflections/new',
    path: '/reflections/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/reflections/new': typeof AuthenticatedReflectionsNewRoute
  '/reflections/': typeof AuthenticatedReflectionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/brain': typeof AuthenticatedBrainRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/reflections/new': typeof AuthenticatedReflectionsNewRoute
  '/reflections': typeof AuthenticatedReflectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/brain': typeof AuthenticatedBrainRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/reflections/new': typeof AuthenticatedReflectionsNewRoute
  '/_authenticated/reflections/': typeof AuthenticatedReflectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brain'
    | '/library'
    | '/settings'
    | '/reflections/new'
    | '/reflections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/brain'
    | '/library'
    | '/settings'
    | '/'
    | '/reflections/new'
    | '/reflections'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/brain'
    | '/_authenticated/library'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/reflections/new'
    | '/_authenticated/reflections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brain': {
      id: '/_authenticated/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AuthenticatedBrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reflections/': {
      id: '/_authenticated/reflections/'
      path: '/reflections'
      fullPath: '/reflections/'
      preLoaderRoute: typeof AuthenticatedReflectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reflections/new': {
      id: '/_authenticated/reflections/new'
      path: '/reflections/new'
      fullPath: '/reflections/new'
      preLoaderRoute: typeof AuthenticatedReflectionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrainRoute: typeof AuthenticatedBrainRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReflectionsNewRoute: typeof AuthenticatedReflectionsNewRoute
  AuthenticatedReflectionsIndexRoute: typeof AuthenticatedReflectionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrainRoute: AuthenticatedBrainRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReflectionsNewRoute: AuthenticatedReflectionsNewRoute,
  AuthenticatedReflectionsIndexRoute: AuthenticatedReflectionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
